// <auto-generated />
using System;
using Editorial.Workflows.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Editorial.Workflows.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Editorial.Workflows.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Editorial.Workflows.Models.WorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowStages");
                });

            modelBuilder.Entity("Editorial.Workflows.Models.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromStageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToStageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowStageId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStageId");

                    b.ToTable("WorkflowTransitions");
                });

            modelBuilder.Entity("Editorial.Workflows.Models.WorkflowStage", b =>
                {
                    b.HasOne("Editorial.Workflows.Models.Workflow", null)
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowId");
                });

            modelBuilder.Entity("Editorial.Workflows.Models.WorkflowTransition", b =>
                {
                    b.HasOne("Editorial.Workflows.Models.WorkflowStage", null)
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowStageId");
                });

            modelBuilder.Entity("Editorial.Workflows.Models.Workflow", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Editorial.Workflows.Models.WorkflowStage", b =>
                {
                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
